### ISSUE TITLE
Add Installer to Tutorial

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Tutorial#3]
OS (if applicable): Windows, Mac
Version: 0.5.0

Would it be helpful to add Makefile code to the Tutorial module to demonstrate using make dist to build an NSIS or Mac installer for the module?  If the installer detects where Rack 0.5.0 is installed and then puts the module pack in the correct place, it might reduce support questions after Rack 0.5.0 is released.

**Comment by AndrewBelt** [comment]
`make dist` in the Rack repo is for making the official build only, it's only needed by me. 

`make dist` for plugins should produce a zip file, which users unzip in their plugins folder.

**Comment by djpeterso23662** [comment]
Sounds good, Andrew! Thanks!
