### ISSUE TITLE
error with tutorial at make

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/Tutorial#4]
src/Tutorial.cpp:16:79: error: use of undeclared identifier 'OSCILLATOR_TAG'
  ..."MyModule", "My Module", OSCILLATOR_TAG));
                              ^
1 error generated.
make: *** [build/src/Tutorial.cpp.o] Error 1

**Comment by michaelpalumbo** [comment]
I hope this is enough info -- if not, let me know! :D

**Comment by AndrewBelt** [comment]
You need to pull the latest version of the Rack source.

**Comment by michaelpalumbo** [comment]
ah ok. done, and i confirm it works.
