### ISSUE TITLE
not a valid identifierline 89: export: `dashless

### ISSUE THREAD

**Issue by janz1961** [VCVRack/Tutorial#6]
I'm new here so it may be that I don't know where to look if this has been reported already.

Today I build the Rack executable thanks to the excelent readme without problems. But when building the Fundamental plugin, I got:

```
$ git submodule update --init --recursive
': not a valid identifierline 89: export: `dashless
```

Could be something with git, but that was also installed according the readme (after I first removed the git client I had already installed).

**Comment by phdsg** [comment]
https://github.com/jeremywen/JW-Modules/wiki/Dev-FAQ-for-VCV-Rack#how-do-i-get-rid-of-this-harmless-error-on-windows

**Comment by janz1961** [comment]
Works. Thanks. I'll make sure I'll read the rest of this FAQ as well.
